#!/bin/bash
set -euo pipefail
. /run/jcloud/control/env.sh

# The root-only envd control service must not become a privilege escalation
# route from an untrusted agent in the same VM (IPv4 and IPv6).
for firewall in iptables ip6tables; do
  "$firewall" -w -C OUTPUT -p tcp --dport 49983 -m owner --uid-owner 10001 -j REJECT 2>/dev/null ||
    "$firewall" -w -A OUTPUT -p tcp --dport 49983 -m owner --uid-owner 10001 -j REJECT
done

unprivileged=(setpriv --reuid=10001 --regid=10001 --clear-groups --bounding-set=-all --inh-caps=-all --ambient-caps=-all --no-new-privs)
mkdir -p /workspace /out /home/jcode/.jcode /run/jcloud/config /run/jcloud/attachments /run/jcloud/lifecycle
chown 10001:10001 /workspace /out /home/jcode /home/jcode/.jcode /run/jcloud/lifecycle
chmod 750 /run/jcloud/lifecycle
if [ -n "${CUBE_RESTORE_URL:-}" ]; then
  mkdir -p /var/lib/jcloud-restore
  chown root:10001 /var/lib/jcloud-restore
  chmod 750 /var/lib/jcloud-restore
  curl --fail --silent --show-error --location --max-time 120 "$CUBE_RESTORE_URL" -o /var/lib/jcloud-restore/archive.tar
  chown root:10001 /var/lib/jcloud-restore/archive.tar
  chmod 640 /var/lib/jcloud-restore/archive.tar
  # Archive contents were generated by an untrusted task. Restore with the
  # runner UID, so a malicious link cannot write to root-owned control paths.
  "${unprivileged[@]}" tar --no-same-owner --same-permissions -xf /var/lib/jcloud-restore/archive.tar -C /
  rm /var/lib/jcloud-restore/archive.tar
fi
for path in /workspace /home/jcode /home/jcode/.jcode; do
  [ -d "$path" ] && [ ! -L "$path" ] || exit 65
done
# Managed Plugin paths are rebuilt on every run, including an empty selection.
"${unprivileged[@]}" mkdir -p /home/jcode/.jcode/skills
[ ! -L /home/jcode/.jcode/skills ] || exit 65
for provider in github gitlab gitea; do
  rm -rf -- "/home/jcode/.jcode/skills/$provider"
  mkdir -p "/home/jcode/.jcode/skills/$provider"
done
rm -f /home/jcode/.jcode/mcp.json
if [ "${CUBE_PLUGIN_ENABLED:-0}" = 1 ]; then
  /run/jcloud/control/plugin-runtime inject --assets /run/jcloud/assets --providers "$CUBE_PLUGIN_PROVIDERS" --dir /run/jcloud/runtime
  chown -R root:10001 /run/jcloud/runtime
  find /run/jcloud/runtime -type d -exec chmod 750 {} +
  find /run/jcloud/runtime -type f -exec chmod 640 {} +
  find /run/jcloud/runtime/bin -type f -exec chmod 750 {} +
  /run/jcloud/control/plugin-runtime sync-credentials --providers "$CUBE_PLUGIN_PROVIDERS" --once --reader-gid 10001 --dir /run/jcloud/plugins
  for provider in github gitlab gitea; do
    mount --bind "/run/jcloud/runtime/skills/$provider" "/home/jcode/.jcode/skills/$provider"
    mount -o remount,bind,ro "/home/jcode/.jcode/skills/$provider"
  done
  touch /home/jcode/.jcode/mcp.json
  mount --bind /run/jcloud/plugins/jtype/mcp.json /home/jcode/.jcode/mcp.json
  mount -o remount,bind,ro /home/jcode/.jcode/mcp.json
fi
/bin/bash /run/jcloud/control/attachments.sh
chown -R root:10001 /run/jcloud/config /run/jcloud/attachments
find /run/jcloud/config /run/jcloud/attachments -type d -exec chmod 750 {} +
find /run/jcloud/config /run/jcloud/attachments -type f -exec chmod 640 {} +
unset CUBE_RESTORE_URL
echo prepared > /run/jcloud/control/prepared
