apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitseed-data
  namespace: jcloud
  labels:
    app.kubernetes.io/name: gitseed
    app.kubernetes.io/part-of: jcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
