// GENERATED by scripts/extract-device-locales.mjs from src/i18n/locales/en.ts.
// Do not hand-edit; re-run the script after changing the console's device.* copy.
export default {
  "run": {
    "toolStatusDone": "Done",
    "toolStatus": {
      "running": "running",
      "failed": "failed",
      "queued": "queued",
      "canceled": "canceled"
    },
    "unknownEvent": "Unknown event: {type}",
    "permission": {
      "label": "permission",
      "required": "permission required",
      "noAction": "No action (cancelled)",
      "timedOut": "timed out",
      "resolved": "resolved",
      "answered": "Answered — waiting for the agent…",
      "readonly": "Read-only — a project member can answer."
    }
  },
  "device": {
    "list": {
      "title": "Devices",
      "subtitle": "jcode devices connected to your account. Send work to any online machine.",
      "emptyTitle": "No devices yet",
      "emptyBody": "Run `jcode login` on a machine to connect it to jcode Cloud.",
      "online": "Online",
      "offline": "Offline",
      "lastSeen": "Last seen {time}",
      "neverSeen": "Never seen",
      "loadErrorTitle": "Could not load devices",
      "servicePrincipal": "Devices are tied to a user account — sign in with a user session, not the console service token.",
      "platformDesktop": "Desktop",
      "platformCli": "CLI",
      "e2ee": "End-to-end encrypted",
      "e2eeWithKeyGen": "End-to-end encrypted · key generation {gen}"
    },
    "welcome": {
      "back": "Devices",
      "newSession": "New session",
      "composerPlaceholder": "Ask jcode anything…",
      "send": "Send",
      "mode": "Mode",
      "sessions": "Sessions",
      "sessionCount_one": "{count} session",
      "sessionCount_other": "{count} sessions",
      "noSessions": "No sessions yet — send a message to start one.",
      "untitled": "Untitled session",
      "offlineBanner": "This device is offline. Messages cannot be sent until it reconnects.",
      "status": {
        "idle": "Idle",
        "running": "Running"
      }
    },
    "session": {
      "back": "Back to device",
      "thinking": "Thinking",
      "thinkingAria": "Thinking…",
      "you": "You",
      "send": "Send",
      "stop": "Stop",
      "composerPlaceholder": "Message jcode…",
      "offlineBanner": "Device offline — sending is disabled until it reconnects.",
      "streamError": "Live stream interrupted — reconnecting…",
      "reconnect": "Reconnect",
      "approve": "Approve",
      "approveAll": "Always allow",
      "deny": "Deny",
      "toolDenied": "denied",
      "askUser": "jcode asked a question (answer it on the device):",
      "agentStarted": "Agent started",
      "agentDone": "Agent finished",
      "agentStopped": "Stopped by user",
      "agentFailed": "Agent failed: {message}",
      "taskRunning": "Session running",
      "taskIdle": "Session idle",
      "modeChanged": "Mode changed to {mode}",
      "modelChanged": "Model changed to {model}",
      "sessionReset": "Session reset",
      "todoUpdated": "Todos updated",
      "goalUpdated": "Goal updated: {objective}",
      "goalCleared": "Goal cleared",
      "subagentStarted": "Subagent {name} started",
      "subagentDone": "Subagent {name} finished",
      "subagentFailed": "Subagent {name} failed",
      "sendFailed": "Could not send: {message}",
      "deviceOffline": "Device is offline",
      "emptyHistory": "No events in this session yet.",
      "source": {
        "console": "Console",
        "mobile": "Mobile",
        "desktop": "Desktop",
        "wechat": "WeChat",
        "local": "Local"
      }
    },
    "guide": {
      "entry": "Usage guide",
      "title": "Using your jcode devices",
      "subtitle": "How to connect a machine with `jcode login` and drive it from the browser or the mobile app.",
      "back": "Back to devices",
      "shots": {
        "devices": "Device list in the cloud console",
        "welcome": "Device page: start a new session and browse existing ones",
        "session": "A session streaming live from the device",
        "offline": "An offline device still shows its history",
        "login": "Sign-in screen of the mobile app"
      },
      "what": {
        "title": "What is a \"device\"?",
        "p1": "A device is a machine running jcode (CLI or desktop) that was signed in to jcode Cloud with `jcode login`. Once connected, you can view and control that machine remotely from the cloud console or the mobile app.",
        "p2": "The cloud only relays traffic: your machine dials out to the cloud, so no inbound ports or VPN are needed. Sessions keep running — and stay stored — on your machine."
      },
      "quickstart": {
        "title": "Quick start",
        "p1": "On the machine you want to control, run:",
        "code1": "jcode login",
        "p2": "The CLI prints a code and a confirmation link — approve the sign-in in your browser. The device then connects automatically and appears in your device list.",
        "p3": "By default jcode signs in to https://cloud.j-code.net. For a self-hosted cloud, pass its URL — it must use https (plain http is only allowed for localhost during development):",
        "code2": "jcode login --cloud https://your-cloud.example.com"
      },
      "remote": {
        "title": "Using a device remotely",
        "p1": "Open the device list and pick a device. From there you can start a new session, follow running sessions live, stop a run, and answer approval prompts — the same controls as on the machine itself.",
        "p2": "When a device is offline you can still read its session history, but sending messages and approvals is disabled until it reconnects."
      },
      "pairing": {
        "title": "Pairing & end-to-end encryption",
        "p1": "Session content is end-to-end encrypted: the cloud only stores ciphertext and routing metadata, so it cannot read your sessions. A new client (a new browser or a phone) must pair with a device before it can decrypt anything.",
        "p2": "Start pairing from the client, then approve it on the device within 10 minutes:",
        "code1": "jcode cloud pairings",
        "code2": "jcode cloud approve <pairing_id>",
        "p3": "`pairings` lists the pending requests with their labels; `approve` authorizes one (reject with `jcode cloud deny <pairing_id>`)."
      },
      "keys": {
        "title": "Keys & recovery",
        "p1": "The encryption key (CEK) is generated on your first device and never leaves your devices in plaintext. Back it up once as a 24-word recovery phrase and keep it somewhere safe:",
        "code1": "jcode cloud key show-phrase",
        "p2": "If every device is lost, restore the key on a freshly signed-in device from the phrase:",
        "code2": "jcode cloud key recover",
        "p3": "To rotate the key (paired clients will need to pair again):",
        "code3": "jcode cloud rotate-key"
      },
      "commands": {
        "title": "Command reference",
        "p1": "The everyday commands, all run on the device:",
        "rows": {
          "login": "Sign this machine in to jcode Cloud (device-code flow).",
          "loginStatus": "Show the current sign-in status and exit.",
          "logout": "Sign out, revoke the device token and remove local credentials.",
          "cloudStatus": "Show cloud URL, device id, key generation and reachability.",
          "pairings": "List pending pairing requests from clients.",
          "approve": "Approve a pairing request (hands the encrypted key to the client).",
          "deny": "Deny a pairing request.",
          "showPhrase": "Reveal the 24-word recovery phrase for the encryption key.",
          "recover": "Rebuild the encryption key from a recovery phrase.",
          "rotateKey": "Generate a new key (key_gen+1); paired clients must re-pair."
        },
        "e2eeNote": "E2E encryption is on by default. To temporarily disable it (plaintext uplink, e.g. for debugging), set \"cloud\": { \"e2ee\": false } in `~/.jcode/config.json` and restart `jcode web`."
      }
    },
    "pairing": {
      "start": "Pair this client",
      "idle": {
        "title": "End-to-end encryption not set up",
        "body": "Pair this browser with the device to read and send encrypted session content. The device stays the only place your key exists in plaintext."
      },
      "pending": {
        "title": "Waiting for approval on the device",
        "body": "Approve this pairing on the device within 10 minutes:"
      },
      "denied": {
        "title": "Pairing denied",
        "body": "The device denied this pairing request. Start a new one if that was a mistake."
      },
      "expired": {
        "title": "Pairing expired",
        "body": "The pairing request was not approved within 10 minutes. Start a new one."
      },
      "error": {
        "title": "Pairing failed",
        "body": "Something went wrong while pairing. Try again."
      }
    },
    "title": "Authorize a device",
    "lede": "A jcode CLI is asking to sign in to this cloud. Enter the code it shows to continue.",
    "codeLabel": "Device code",
    "codeHint": "The 8-character code shown by `jcode login`, e.g. XXXX-XXXX.",
    "codeRequired": "Enter the code shown by the CLI.",
    "continue": "Continue",
    "confirmTitle": "Is this your device?",
    "confirmBody": "Approve only if this code matches what your `jcode login` is showing right now.",
    "approve": "Approve",
    "deny": "Deny",
    "approvedTitle": "Device approved",
    "approvedBody": "The CLI can finish signing in now — you can close this page.",
    "deniedTitle": "Device denied",
    "deniedBody": "The sign-in request was rejected. The CLI will stop waiting.",
    "another": "Authorize another device",
    "errorNotFound": "No pending sign-in matches that code — it may have expired. Run `jcode login` again.",
    "errorAlreadyDecided": "That sign-in was already approved or denied.",
    "errorGeneric": "Could not authorize the device. Try again."
  }
};
