// GENERATED by scripts/extract-device-locales.mjs from src/i18n/locales/en.ts.
// Do not hand-edit; re-run the script after changing the console's device.* copy.
export default {
  "run": {
    "toolStatusDone": "Done",
    "toolStatus": {
      "running": "running",
      "failed": "failed",
      "queued": "queued",
      "canceled": "canceled"
    },
    "unknownEvent": "Unknown event: {type}",
    "permission": {
      "label": "permission",
      "required": "permission required",
      "noAction": "No action (cancelled)",
      "timedOut": "timed out",
      "resolved": "resolved",
      "answered": "Answered — waiting for the agent…",
      "readonly": "Read-only — a project member can answer."
    }
  },
  "device": {
    "list": {
      "title": "Devices",
      "subtitle": "jcode devices connected to your account. Send work to any online machine.",
      "emptyTitle": "No devices yet",
      "emptyBody": "Run `jcode login` on a machine to connect it to jcode Cloud.",
      "online": "Online",
      "offline": "Offline",
      "lastSeen": "Last seen {time}",
      "neverSeen": "Never seen",
      "loadErrorTitle": "Could not load devices",
      "servicePrincipal": "Devices are tied to a user account — sign in with a user session, not the console service token."
    },
    "welcome": {
      "back": "Devices",
      "newSession": "New session",
      "composerPlaceholder": "Ask jcode anything…",
      "send": "Send",
      "mode": "Mode",
      "sessions": "Sessions",
      "sessionCount_one": "{count} session",
      "sessionCount_other": "{count} sessions",
      "noSessions": "No sessions yet — send a message to start one.",
      "untitled": "Untitled session",
      "offlineBanner": "This device is offline. Messages cannot be sent until it reconnects.",
      "status": {
        "idle": "Idle",
        "running": "Running"
      }
    },
    "session": {
      "back": "Back to device",
      "thinking": "Thinking",
      "thinkingAria": "Thinking…",
      "you": "You",
      "send": "Send",
      "stop": "Stop",
      "composerPlaceholder": "Message jcode…",
      "offlineBanner": "Device offline — sending is disabled until it reconnects.",
      "streamError": "Live stream interrupted — reconnecting…",
      "reconnect": "Reconnect",
      "approve": "Approve",
      "approveAll": "Always allow",
      "deny": "Deny",
      "toolDenied": "denied",
      "askUser": "jcode asked a question (answer it on the device):",
      "agentStarted": "Agent started",
      "agentDone": "Agent finished",
      "agentStopped": "Stopped by user",
      "agentFailed": "Agent failed: {message}",
      "taskRunning": "Session running",
      "taskIdle": "Session idle",
      "modeChanged": "Mode changed to {mode}",
      "modelChanged": "Model changed to {model}",
      "sessionReset": "Session reset",
      "todoUpdated": "Todos updated",
      "goalUpdated": "Goal updated: {objective}",
      "goalCleared": "Goal cleared",
      "subagentStarted": "Subagent {name} started",
      "subagentDone": "Subagent {name} finished",
      "subagentFailed": "Subagent {name} failed",
      "sendFailed": "Could not send: {message}",
      "deviceOffline": "Device is offline",
      "emptyHistory": "No events in this session yet."
    },
    "pairing": {
      "start": "Pair this client",
      "idle": {
        "title": "End-to-end encryption not set up",
        "body": "Pair this browser with the device to read and send encrypted session content. The device stays the only place your key exists in plaintext."
      },
      "pending": {
        "title": "Waiting for approval on the device",
        "body": "Approve this pairing on the device within 10 minutes:"
      },
      "denied": {
        "title": "Pairing denied",
        "body": "The device denied this pairing request. Start a new one if that was a mistake."
      },
      "expired": {
        "title": "Pairing expired",
        "body": "The pairing request was not approved within 10 minutes. Start a new one."
      },
      "error": {
        "title": "Pairing failed",
        "body": "Something went wrong while pairing. Try again."
      }
    },
    "title": "Authorize a device",
    "lede": "A jcode CLI is asking to sign in to this cloud. Enter the code it shows to continue.",
    "codeLabel": "Device code",
    "codeHint": "The 8-character code shown by `jcode login`, e.g. XXXX-XXXX.",
    "codeRequired": "Enter the code shown by the CLI.",
    "continue": "Continue",
    "confirmTitle": "Is this your device?",
    "confirmBody": "Approve only if this code matches what your `jcode login` is showing right now.",
    "approve": "Approve",
    "deny": "Deny",
    "approvedTitle": "Device approved",
    "approvedBody": "The CLI can finish signing in now — you can close this page.",
    "deniedTitle": "Device denied",
    "deniedBody": "The sign-in request was rejected. The CLI will stop waiting.",
    "another": "Authorize another device",
    "errorNotFound": "No pending sign-in matches that code — it may have expired. Run `jcode login` again.",
    "errorAlreadyDecided": "That sign-in was already approved or denied.",
    "errorGeneric": "Could not authorize the device. Try again."
  }
};
