// GENERATED by scripts/extract-device-locales.mjs from src/i18n/locales/ja.ts.
// Do not hand-edit; re-run the script after changing the console's device.* copy.
export default {
  "run": {
    "toolStatusDone": "完了",
    "toolStatus": {
      "running": "実行中",
      "failed": "失敗",
      "queued": "キュー待ち",
      "canceled": "キャンセル済み"
    },
    "unknownEvent": "不明なイベント: {type}",
    "permission": {
      "label": "権限",
      "required": "権限が必要です",
      "noAction": "操作なし（キャンセル済み）",
      "timedOut": "タイムアウトしました",
      "resolved": "解決済み",
      "answered": "回答済み — エージェントを待っています…",
      "readonly": "読み取り専用 — プロジェクトメンバーが回答できます。"
    }
  },
  "device": {
    "list": {
      "title": "デバイス",
      "subtitle": "アカウントに接続されている jcode デバイス。オンラインのマシンに作業を送信できます。",
      "emptyTitle": "デバイスがまだありません",
      "emptyBody": "マシン上で `jcode login` を実行して、jcode Cloud に接続してください。",
      "online": "オンライン",
      "offline": "オフライン",
      "lastSeen": "最終確認 {time}",
      "neverSeen": "未接続",
      "loadErrorTitle": "デバイスを読み込めませんでした",
      "servicePrincipal": "デバイスはユーザーアカウントに紐づいています。コンソールのサービストークンではなく、ユーザーセッションでサインインしてください。"
    },
    "welcome": {
      "back": "デバイス",
      "newSession": "新しいセッション",
      "composerPlaceholder": "jcode に何でも聞いてください…",
      "send": "送信",
      "mode": "モード",
      "sessions": "セッション",
      "sessionCount_one": "{count} 件のセッション",
      "sessionCount_other": "{count} 件のセッション",
      "noSessions": "セッションがまだありません。メッセージを送信して開始してください。",
      "untitled": "無題のセッション",
      "offlineBanner": "このデバイスはオフラインです。再接続されるまでメッセージを送信できません。",
      "status": {
        "idle": "アイドル",
        "running": "実行中"
      }
    },
    "session": {
      "back": "デバイスに戻る",
      "thinking": "考え中",
      "thinkingAria": "考え中…",
      "you": "あなた",
      "send": "送信",
      "stop": "停止",
      "composerPlaceholder": "jcode へのメッセージ…",
      "offlineBanner": "デバイスがオフラインです。再接続されるまで送信は無効です。",
      "streamError": "ライブストリームが中断されました。再接続しています…",
      "reconnect": "再接続",
      "approve": "承認",
      "approveAll": "常に許可",
      "deny": "拒否",
      "toolDenied": "拒否されました",
      "askUser": "jcode から質問があります（デバイス上で回答してください）:",
      "agentStarted": "エージェントが開始しました",
      "agentDone": "エージェントが完了しました",
      "agentStopped": "ユーザーによって停止されました",
      "agentFailed": "エージェントが失敗しました: {message}",
      "taskRunning": "セッション実行中",
      "taskIdle": "セッションはアイドルです",
      "modeChanged": "モードが {mode} に変更されました",
      "modelChanged": "モデルが {model} に変更されました",
      "sessionReset": "セッションがリセットされました",
      "todoUpdated": "Todo が更新されました",
      "goalUpdated": "ゴールが更新されました: {objective}",
      "goalCleared": "ゴールがクリアされました",
      "subagentStarted": "サブエージェント {name} が開始しました",
      "subagentDone": "サブエージェント {name} が完了しました",
      "subagentFailed": "サブエージェント {name} が失敗しました",
      "sendFailed": "送信できませんでした: {message}",
      "deviceOffline": "デバイスはオフラインです",
      "emptyHistory": "このセッションにはまだイベントがありません。"
    },
    "guide": {
      "entry": "利用ガイド",
      "title": "jcode デバイスの使い方",
      "subtitle": "`jcode login` でマシンを接続し、ブラウザやモバイルアプリから操作する方法。",
      "back": "デバイス一覧に戻る",
      "shots": {
        "devices": "クラウドコンソールのデバイス一覧",
        "welcome": "デバイスページ：新しいセッションの開始と既存セッションの参照",
        "session": "デバイスからライブ配信されるセッション",
        "offline": "オフラインのデバイスでも履歴を表示",
        "login": "モバイルアプリのサインイン画面"
      },
      "what": {
        "title": "「デバイス」とは？",
        "p1": "デバイスとは、jcode（CLI またはデスクトップ）を実行し、`jcode login` で jcode Cloud にサインインしたマシンのことです。接続後は、クラウドコンソールやモバイルアプリからそのマシンをリモートで表示・操作できます。",
        "p2": "クラウドはトラフィックを中継するだけです。マシン側からクラウドへ外向きに接続するため、受信ポートや VPN は不要です。セッションは常にマシン上で実行・保存されます。"
      },
      "quickstart": {
        "title": "クイックスタート",
        "p1": "操作したいマシンで次を実行します：",
        "code1": "jcode login",
        "p2": "CLI がコードと確認リンクを表示します。ブラウザでサインインを承認してください。その後デバイスは自動的に接続され、デバイス一覧に表示されます。",
        "p3": "デフォルトでは https://cloud.j-code.net にサインインします。セルフホストの場合は URL を指定してください。https が必須です（平文 http は開発時の localhost のみ許可）：",
        "code2": "jcode login --cloud https://your-cloud.example.com"
      },
      "remote": {
        "title": "デバイスのリモート操作",
        "p1": "デバイス一覧を開き、デバイスを選択します。新しいセッションの開始、実行中セッションのライブ表示、実行の停止、承認プロンプトへの応答など、マシン本体と同じ操作ができます。",
        "p2": "デバイスがオフラインのときもセッション履歴は読めますが、メッセージ送信と承認は再接続されるまで無効になります。"
      },
      "pairing": {
        "title": "ペアリングとエンドツーエンド暗号",
        "p1": "セッション内容はエンドツーエンドで暗号化されています。クラウドには暗号文とルーティング用メタデータしか保存されず、セッションを読むことはできません。新しいクライアント（新しいブラウザやスマートフォン）は、復号する前にデバイスとペアリングする必要があります。",
        "p2": "クライアント側でペアリングを開始し、10 分以内にデバイス上で承認します：",
        "code1": "jcode cloud pairings",
        "code2": "jcode cloud approve <pairing_id>",
        "p3": "`pairings` は保留中のリクエストをラベル付きで一覧し、`approve` で承認します（拒否は `jcode cloud deny <pairing_id>`）。"
      },
      "keys": {
        "title": "鍵とリカバリー",
        "p1": "暗号鍵（CEK）は最初のデバイスで生成され、平文でデバイスの外に出ることはありません。24 語のリカバリーフレーズとして一度バックアップし、安全な場所に保管してください：",
        "code1": "jcode cloud key show-phrase",
        "p2": "すべてのデバイスを失った場合は、新しくサインインしたデバイスでフレーズから鍵を復元します：",
        "code2": "jcode cloud key recover",
        "p3": "鍵をローテーションする場合（ペアリング済みクライアントは再ペアリングが必要）：",
        "code3": "jcode cloud rotate-key"
      },
      "commands": {
        "title": "コマンドリファレンス",
        "p1": "日常使いのコマンド（すべてデバイス上で実行）：",
        "rows": {
          "login": "このマシンを jcode Cloud にサインインします（デバイスコードフロー）。",
          "loginStatus": "現在のサインイン状態を表示して終了します。",
          "logout": "サインアウトし、デバイストークンを失効させ、ローカル資格情報を削除します。",
          "cloudStatus": "クラウド URL、デバイス ID、鍵世代、到達可能性を表示します。",
          "pairings": "クライアントからの保留中ペアリングリクエストを一覧します。",
          "approve": "ペアリングリクエストを承認します（暗号化された鍵をクライアントへ渡します）。",
          "deny": "ペアリングリクエストを拒否します。",
          "showPhrase": "暗号鍵の 24 語リカバリーフレーズを表示します。",
          "recover": "リカバリーフレーズから暗号鍵を再構築します。",
          "rotateKey": "新しい鍵を生成します（key_gen+1）。ペアリング済みクライアントは再ペアリングが必要です。"
        },
        "e2eeNote": "E2E 暗号はデフォルトで有効です。一時的に無効にする（平文アップリンク、デバッグ用）には、`~/.jcode/config.json` に \"cloud\": { \"e2ee\": false } を設定して `jcode web` を再起動してください。"
      }
    },
    "pairing": {
      "start": "このクライアントをペアリング",
      "idle": {
        "title": "エンドツーエンド暗号化が未設定です",
        "body": "このブラウザをデバイスとペアリングすると、暗号化されたセッション内容を読み書きできます。鍵の平文はデバイス上にのみ存在します。"
      },
      "pending": {
        "title": "デバイスでの承認待ち",
        "body": "10 分以内にデバイス上でこのペアリングを承認してください:"
      },
      "denied": {
        "title": "ペアリングが拒否されました",
        "body": "デバイスがこのペアリング要求を拒否しました。誤りであれば新しく開始してください。"
      },
      "expired": {
        "title": "ペアリングの期限切れ",
        "body": "ペアリング要求が 10 分以内に承認されませんでした。新しく開始してください。"
      },
      "error": {
        "title": "ペアリングに失敗しました",
        "body": "ペアリング中に問題が発生しました。もう一度お試しください。"
      }
    },
    "title": "デバイスを承認",
    "lede": "jcode CLI がこのクラウドへのサインインを要求しています。表示されているコードを入力して続行してください。",
    "codeLabel": "デバイスコード",
    "codeHint": "`jcode login` に表示される 8 文字のコード（例: XXXX-XXXX）。",
    "codeRequired": "CLI に表示されているコードを入力してください。",
    "continue": "続行",
    "confirmTitle": "このデバイスはあなたのものですか？",
    "confirmBody": "このコードが実行中の `jcode login` に表示されているものと一致する場合のみ承認してください。",
    "approve": "承認",
    "deny": "拒否",
    "approvedTitle": "デバイスを承認しました",
    "approvedBody": "CLI がサインインを完了できます。このページは閉じて構いません。",
    "deniedTitle": "デバイスを拒否しました",
    "deniedBody": "サインイン要求は拒否されました。CLI は待機を停止します。",
    "another": "別のデバイスを承認",
    "errorNotFound": "そのコードに一致する保留中のサインインはありません。期限切れの可能性があります。`jcode login` を再実行してください。",
    "errorAlreadyDecided": "そのサインインはすでに承認または拒否されています。",
    "errorGeneric": "デバイスを承認できませんでした。もう一度お試しください。"
  }
};
