// GENERATED by scripts/extract-device-locales.mjs from src/i18n/locales/ko.ts.
// Do not hand-edit; re-run the script after changing the console's device.* copy.
export default {
  "run": {
    "toolStatusDone": "완료",
    "toolStatus": {
      "running": "실행 중",
      "failed": "실패",
      "queued": "대기 중",
      "canceled": "취소됨"
    },
    "unknownEvent": "알 수 없는 이벤트: {type}",
    "permission": {
      "label": "권한",
      "required": "권한 필요",
      "noAction": "작업 없음 (취소됨)",
      "timedOut": "시간 초과",
      "resolved": "처리됨",
      "answered": "응답함 — 에이전트를 기다리는 중…",
      "readonly": "읽기 전용 — 프로젝트 멤버가 응답할 수 있습니다."
    }
  },
  "device": {
    "compose": {
      "project": "프로젝트 디렉터리",
      "model": "모델",
      "effort": "강도",
      "goal": "목표",
      "goalPlaceholder": "이 세션에서 달성할 것은 무엇인가요?",
      "attachments": "첨부 파일",
      "attachAdd": "파일 첨부",
      "removeAttachment": "{name} 제거",
      "deviceDefault": "디바이스 기본값",
      "attachmentTooBig": "{name} 파일이 2MB를 초과합니다 — 더 작은 파일을 선택하세요.",
      "attachmentTooMany": "메시지당 첨부 파일은 최대 {max}개입니다.",
      "attachmentImage": "{name} 파일은 이미지입니다 — 이미지는 아직 지원되지 않습니다."
    },
    "list": {
      "title": "기기",
      "subtitle": "계정에 연결된 jcode 기기입니다. 온라인 상태의 모든 머신에 작업을 보낼 수 있습니다.",
      "emptyTitle": "아직 기기가 없습니다",
      "emptyBody": "머신에서 `jcode login`을 실행하여 jcode Cloud에 연결하세요.",
      "online": "온라인",
      "offline": "오프라인",
      "lastSeen": "마지막 확인 {time}",
      "neverSeen": "확인된 적 없음",
      "loadErrorTitle": "기기를 불러올 수 없습니다",
      "servicePrincipal": "기기는 사용자 계정에 연결됩니다. 콘솔 서비스 토큰이 아닌 사용자 세션으로 로그인하세요.",
      "platformDesktop": "데스크톱",
      "platformCli": "CLI",
      "e2ee": "종단간 암호화",
      "e2eeWithKeyGen": "종단간 암호화 · 키 세대 {gen}"
    },
    "welcome": {
      "back": "기기",
      "newSession": "새 세션",
      "composerPlaceholder": "jcode에게 무엇이든 물어보세요…",
      "send": "보내기",
      "mode": "모드",
      "sessions": "세션",
      "sessionCount_one": "{count}개 세션",
      "sessionCount_other": "{count}개 세션",
      "noSessions": "아직 세션이 없습니다. 메시지를 보내 시작하세요.",
      "untitled": "제목 없는 세션",
      "offlineBanner": "이 기기는 오프라인입니다. 다시 연결될 때까지 메시지를 보낼 수 없습니다.",
      "status": {
        "idle": "유휴",
        "running": "실행 중"
      }
    },
    "session": {
      "back": "기기로 돌아가기",
      "thinking": "생각 중",
      "thinkingAria": "생각 중…",
      "you": "나",
      "send": "보내기",
      "stop": "중지",
      "composerPlaceholder": "jcode에 메시지 보내기…",
      "offlineBanner": "기기가 오프라인입니다. 다시 연결될 때까지 전송이 비활성화됩니다.",
      "streamError": "라이브 스트림이 중단되었습니다. 다시 연결 중…",
      "reconnect": "다시 연결",
      "approve": "승인",
      "approveAll": "항상 허용",
      "deny": "거부",
      "toolDenied": "거부됨",
      "askUser": "jcode가 질문했습니다(기기에서 답변하세요):",
      "agentStarted": "에이전트가 시작되었습니다",
      "agentDone": "에이전트가 완료되었습니다",
      "agentStopped": "사용자가 중지했습니다",
      "agentFailed": "에이전트 실패: {message}",
      "taskRunning": "세션 실행 중",
      "taskIdle": "세션 유휴 상태",
      "modeChanged": "모드가 {mode}(으)로 변경되었습니다",
      "modelChanged": "모델이 {model}(으)로 변경되었습니다",
      "sessionReset": "세션이 초기화되었습니다",
      "todoUpdated": "할 일이 업데이트되었습니다",
      "goalUpdated": "목표가 업데이트되었습니다: {objective}",
      "goalCleared": "목표가 지워졌습니다",
      "subagentStarted": "하위 에이전트 {name}이(가) 시작되었습니다",
      "subagentDone": "하위 에이전트 {name}이(가) 완료되었습니다",
      "subagentFailed": "하위 에이전트 {name}이(가) 실패했습니다",
      "sendFailed": "보낼 수 없습니다: {message}",
      "deviceOffline": "기기가 오프라인입니다",
      "emptyHistory": "이 세션에는 아직 이벤트가 없습니다.",
      "source": {
        "console": "콘솔",
        "mobile": "모바일",
        "desktop": "데스크톱",
        "wechat": "WeChat",
        "local": "로컬"
      }
    },
    "guide": {
      "entry": "사용 가이드",
      "title": "jcode 디바이스 사용하기",
      "subtitle": "`jcode login`으로 머신을 연결하고 브라우저나 모바일 앱에서 제어하는 방법.",
      "back": "디바이스 목록으로",
      "shots": {
        "devices": "클우드 콘솔의 디바이스 목록",
        "welcome": "디바이스 페이지: 새 세션 시작과 기존 세션 탐색",
        "session": "디바이스에서 실시간으로 스트리밍되는 세션",
        "offline": "오프라인 디바이스도 히스토리를 보여줍니다",
        "login": "모바일 앱 로그인 화면"
      },
      "what": {
        "title": "\"디바이스\"란?",
        "p1": "디바이스는 jcode(CLI 또는 데스크톱)를 실행하고 `jcode login`으로 jcode Cloud에 로그인한 머신입니다. 연결되면 클라우드 콘솔이나 모바일 앱에서 그 머신을 원격으로 보고 제어할 수 있습니다.",
        "p2": "클우드는 트래픽을 중계할 뿐입니다. 머신이 클라우드로 아웃바운드 연결을 하므로 인바운드 포트나 VPN이 필요 없습니다. 세션은 항상 머신에서 실행되고 저장됩니다."
      },
      "quickstart": {
        "title": "빠른 시작",
        "p1": "제어하려는 머신에서 실행하세요:",
        "code1": "jcode login",
        "p2": "CLI가 코드와 확인 링크를 출력합니다. 브라우저에서 로그인을 승인하세요. 이후 디바이스가 자동으로 연결되어 디바이스 목록에 나타납니다.",
        "p3": "기본값은 https://cloud.j-code.net입니다. 셀프 호스팅이라면 URL을 전달하세요. https여야 합니다(일반 http는 개발용 localhost만 허용):",
        "code2": "jcode login --cloud https://your-cloud.example.com"
      },
      "remote": {
        "title": "디바이스 원격 사용",
        "p1": "디바이스 목록을 열고 디바이스를 선택하세요. 새 세션 시작, 실행 중 세션 실시간 보기, 실행 중지, 승인 프롬프트 응답 등 머신 본체와 같은 조작이 가능합니다.",
        "p2": "디바이스가 오프라인이어도 세션 히스토리는 볼 수 있지만, 메시지 전송과 승인은 다시 연결될 때까지 비활성화됩니다."
      },
      "pairing": {
        "title": "페어링과 종단간 암호화",
        "p1": "세션 내용은 종단간 암호화됩니다. 클라우드에는 암호문과 라우팅 메타데이터만 저장되므로 세션을 읽을 수 없습니다. 새 클라이언트(새 브라우저나 휴폰)는 내용을 복호화하기 전에 디바이스와 페어링해야 합니다.",
        "p2": "클라이언트에서 페어링을 시작한 뒤 10분 이내에 디바이스에서 승인하세요:",
        "code1": "jcode cloud pairings",
        "code2": "jcode cloud approve <pairing_id>",
        "p3": "`pairings`는 대기 중인 요청을 라벨과 함께 보여주고, `approve`로 승인합니다(거절은 `jcode cloud deny <pairing_id>`)."
      },
      "keys": {
        "title": "키와 복구",
        "p1": "암호화 키(CEK)는 첫 디바이스에서 생성되며 평문으로 디바이스 밖에 나가지 않습니다. 24단어 복구 구문으로 한 번 백업해 안전한 곳에 보관하세요:",
        "code1": "jcode cloud key show-phrase",
        "p2": "모든 디바이스를 잃어버렸다면, 새로 로그인한 디바이스에서 구문으로 키를 복구합니다:",
        "code2": "jcode cloud key recover",
        "p3": "키를 교체하려면(페어링된 클라이언트는 다시 페어링 필요):",
        "code3": "jcode cloud rotate-key"
      },
      "commands": {
        "title": "명령어 레퍼런스",
        "p1": "자주 쓰는 명령어(모두 디바이스에서 실행):",
        "rows": {
          "login": "이 머신을 jcode Cloud에 로그인합니다(디바이스 코드 플로우).",
          "loginStatus": "현재 로그인 상태를 표시하고 종료합니다.",
          "logout": "로그아웃하고 디바이스 토큰을 폐기하며 로컬 자격 증명을 삭제합니다.",
          "cloudStatus": "클우드 URL, 디바이스 ID, 키 세대, 연결 상태를 표시합니다.",
          "pairings": "클라이언트의 대기 중인 페어링 요청을 나열합니다.",
          "approve": "페어링 요청을 승인합니다(암호화된 키를 클라이언트에 전달).",
          "deny": "페어링 요청을 거절합니다.",
          "showPhrase": "암호화 키의 24단어 복구 구문을 표시합니다.",
          "recover": "복구 구문으로 암호화 키를 재구성합니다.",
          "rotateKey": "새 키를 생성합니다(key_gen+1). 페어링된 클라이언트는 다시 페어링해야 합니다."
        },
        "e2eeNote": "E2E 암호화는 기본적으로 켜져 있습니다. 일시적으로 끄려면(평문 업링크, 디버깅용) `~/.jcode/config.json`에 \"cloud\": { \"e2ee\": false }를 설정하고 `jcode web`을 재시작하세요."
      }
    },
    "pairing": {
      "start": "이 클라이언트 페어링",
      "idle": {
        "title": "종단 간 암호화가 설정되지 않았습니다",
        "body": "이 브라우저를 기기와 페어링해야 암호화된 세션 내용을 읽고 볼 수 있습니다. 키의 평문은 기기에만 존재합니다."
      },
      "pending": {
        "title": "기기 승인 대기 중",
        "body": "10분 이내에 기기에서 이 페어링을 승인하세요:"
      },
      "denied": {
        "title": "페어링이 거부되었습니다",
        "body": "기기가 이 페어링 요청을 거부했습니다. 실수였다면 새로 시작하세요."
      },
      "expired": {
        "title": "페어링이 만료되었습니다",
        "body": "페어링 요청이 10분 이내에 승인되지 않았습니다. 새로 시작하세요."
      },
      "gate": {
        "title": "페어링 필요",
        "body": "이 기기는 종단 간 암호화를 강제합니다. 페어링이 완료되기 전까지 세션 내용과 제어를 사용할 수 없습니다."
      },
      "error": {
        "title": "페어링 실패",
        "body": "페어링 중 문제가 발생했습니다. 다시 시도하세요."
      }
    },
    "title": "기기 승인",
    "lede": "jcode CLI가 이 클라우드에 로그인을 요청하고 있습니다. 표시된 코드를 입력해 계속하세요.",
    "codeLabel": "기기 코드",
    "codeHint": "`jcode login`에 표시된 8자리 코드입니다(예: XXXX-XXXX).",
    "codeRequired": "CLI에 표시된 코드를 입력하세요.",
    "continue": "계속",
    "confirmTitle": "이 기기가 본인의 기기인가요?",
    "confirmBody": "이 코드가 지금 실행 중인 `jcode login`에 표시된 것과 일치할 때만 승인하세요.",
    "approve": "승인",
    "deny": "거부",
    "approvedTitle": "기기가 승인되었습니다",
    "approvedBody": "이제 CLI가 로그인을 완료할 수 있습니다. 이 페이지를 닫아도 됩니다.",
    "deniedTitle": "기기가 거부되었습니다",
    "deniedBody": "로그인 요청이 거부되었습니다. CLI가 대기를 중단합니다.",
    "another": "다른 기기 승인",
    "errorNotFound": "해당 코드와 일치하는 대기 중인 로그인이 없습니다. 만료되었을 수 있습니다. `jcode login`을 다시 실행하세요.",
    "errorAlreadyDecided": "해당 로그인은 이미 승인 또는 거부되었습니다.",
    "errorGeneric": "기기를 승인할 수 없습니다. 다시 시도하세요."
  }
};
