// GENERATED by scripts/extract-device-locales.mjs from src/i18n/locales/ko.ts.
// Do not hand-edit; re-run the script after changing the console's device.* copy.
export default {
  "run": {
    "toolStatusDone": "완료",
    "toolStatus": {
      "running": "실행 중",
      "failed": "실패",
      "queued": "대기 중",
      "canceled": "취소됨"
    },
    "unknownEvent": "알 수 없는 이벤트: {type}",
    "permission": {
      "label": "권한",
      "required": "권한 필요",
      "noAction": "작업 없음 (취소됨)",
      "timedOut": "시간 초과",
      "resolved": "처리됨",
      "answered": "응답함 — 에이전트를 기다리는 중…",
      "readonly": "읽기 전용 — 프로젝트 멤버가 응답할 수 있습니다."
    }
  },
  "device": {
    "list": {
      "title": "기기",
      "subtitle": "계정에 연결된 jcode 기기입니다. 온라인 상태의 모든 머신에 작업을 보낼 수 있습니다.",
      "emptyTitle": "아직 기기가 없습니다",
      "emptyBody": "머신에서 `jcode login`을 실행하여 jcode Cloud에 연결하세요.",
      "online": "온라인",
      "offline": "오프라인",
      "lastSeen": "마지막 확인 {time}",
      "neverSeen": "확인된 적 없음",
      "loadErrorTitle": "기기를 불러올 수 없습니다",
      "servicePrincipal": "기기는 사용자 계정에 연결됩니다. 콘솔 서비스 토큰이 아닌 사용자 세션으로 로그인하세요."
    },
    "welcome": {
      "back": "기기",
      "newSession": "새 세션",
      "composerPlaceholder": "jcode에게 무엇이든 물어보세요…",
      "send": "보내기",
      "mode": "모드",
      "sessions": "세션",
      "sessionCount_one": "{count}개 세션",
      "sessionCount_other": "{count}개 세션",
      "noSessions": "아직 세션이 없습니다. 메시지를 보내 시작하세요.",
      "untitled": "제목 없는 세션",
      "offlineBanner": "이 기기는 오프라인입니다. 다시 연결될 때까지 메시지를 보낼 수 없습니다.",
      "status": {
        "idle": "유휴",
        "running": "실행 중"
      }
    },
    "session": {
      "back": "기기로 돌아가기",
      "thinking": "생각 중",
      "thinkingAria": "생각 중…",
      "you": "나",
      "send": "보내기",
      "stop": "중지",
      "composerPlaceholder": "jcode에 메시지 보내기…",
      "offlineBanner": "기기가 오프라인입니다. 다시 연결될 때까지 전송이 비활성화됩니다.",
      "streamError": "라이브 스트림이 중단되었습니다. 다시 연결 중…",
      "reconnect": "다시 연결",
      "approve": "승인",
      "approveAll": "항상 허용",
      "deny": "거부",
      "toolDenied": "거부됨",
      "askUser": "jcode가 질문했습니다(기기에서 답변하세요):",
      "agentStarted": "에이전트가 시작되었습니다",
      "agentDone": "에이전트가 완료되었습니다",
      "agentStopped": "사용자가 중지했습니다",
      "agentFailed": "에이전트 실패: {message}",
      "taskRunning": "세션 실행 중",
      "taskIdle": "세션 유휴 상태",
      "modeChanged": "모드가 {mode}(으)로 변경되었습니다",
      "modelChanged": "모델이 {model}(으)로 변경되었습니다",
      "sessionReset": "세션이 초기화되었습니다",
      "todoUpdated": "할 일이 업데이트되었습니다",
      "goalUpdated": "목표가 업데이트되었습니다: {objective}",
      "goalCleared": "목표가 지워졌습니다",
      "subagentStarted": "하위 에이전트 {name}이(가) 시작되었습니다",
      "subagentDone": "하위 에이전트 {name}이(가) 완료되었습니다",
      "subagentFailed": "하위 에이전트 {name}이(가) 실패했습니다",
      "sendFailed": "보낼 수 없습니다: {message}",
      "deviceOffline": "기기가 오프라인입니다",
      "emptyHistory": "이 세션에는 아직 이벤트가 없습니다."
    },
    "pairing": {
      "start": "이 클라이언트 페어링",
      "idle": {
        "title": "종단 간 암호화가 설정되지 않았습니다",
        "body": "이 브라우저를 기기와 페어링해야 암호화된 세션 내용을 읽고 볼 수 있습니다. 키의 평문은 기기에만 존재합니다."
      },
      "pending": {
        "title": "기기 승인 대기 중",
        "body": "10분 이내에 기기에서 이 페어링을 승인하세요:"
      },
      "denied": {
        "title": "페어링이 거부되었습니다",
        "body": "기기가 이 페어링 요청을 거부했습니다. 실수였다면 새로 시작하세요."
      },
      "expired": {
        "title": "페어링이 만료되었습니다",
        "body": "페어링 요청이 10분 이내에 승인되지 않았습니다. 새로 시작하세요."
      },
      "error": {
        "title": "페어링 실패",
        "body": "페어링 중 문제가 발생했습니다. 다시 시도하세요."
      }
    },
    "title": "기기 승인",
    "lede": "jcode CLI가 이 클라우드에 로그인을 요청하고 있습니다. 표시된 코드를 입력해 계속하세요.",
    "codeLabel": "기기 코드",
    "codeHint": "`jcode login`에 표시된 8자리 코드입니다(예: XXXX-XXXX).",
    "codeRequired": "CLI에 표시된 코드를 입력하세요.",
    "continue": "계속",
    "confirmTitle": "이 기기가 본인의 기기인가요?",
    "confirmBody": "이 코드가 지금 실행 중인 `jcode login`에 표시된 것과 일치할 때만 승인하세요.",
    "approve": "승인",
    "deny": "거부",
    "approvedTitle": "기기가 승인되었습니다",
    "approvedBody": "이제 CLI가 로그인을 완료할 수 있습니다. 이 페이지를 닫아도 됩니다.",
    "deniedTitle": "기기가 거부되었습니다",
    "deniedBody": "로그인 요청이 거부되었습니다. CLI가 대기를 중단합니다.",
    "another": "다른 기기 승인",
    "errorNotFound": "해당 코드와 일치하는 대기 중인 로그인이 없습니다. 만료되었을 수 있습니다. `jcode login`을 다시 실행하세요.",
    "errorAlreadyDecided": "해당 로그인은 이미 승인 또는 거부되었습니다.",
    "errorGeneric": "기기를 승인할 수 없습니다. 다시 시도하세요."
  }
};
