// GENERATED by scripts/extract-device-locales.mjs from src/i18n/locales/zh-Hans.ts.
// Do not hand-edit; re-run the script after changing the console's device.* copy.
export default {
  "run": {
    "toolStatusDone": "完成",
    "toolStatus": {
      "running": "运行中",
      "failed": "失败",
      "queued": "排队中",
      "canceled": "已取消"
    },
    "unknownEvent": "未知事件：{type}",
    "permission": {
      "label": "权限",
      "required": "需要权限",
      "noAction": "无操作（已取消）",
      "timedOut": "已超时",
      "resolved": "已解决",
      "answered": "已回答 — 等待 agent…",
      "readonly": "只读 — 项目成员可以回答。"
    }
  },
  "device": {
    "list": {
      "title": "设备",
      "subtitle": "连接到你账号的 jcode 设备。可以把工作发送到任何一台在线机器。",
      "emptyTitle": "还没有设备",
      "emptyBody": "在一台机器上运行 `jcode login`，把它连接到 jcode Cloud。",
      "online": "在线",
      "offline": "离线",
      "lastSeen": "最近在线 {time}",
      "neverSeen": "从未上线",
      "loadErrorTitle": "无法加载设备",
      "servicePrincipal": "设备与用户账号绑定——请以用户身份登录，而不是使用控制台服务令牌。"
    },
    "welcome": {
      "back": "设备",
      "newSession": "新会话",
      "composerPlaceholder": "向 jcode 提问…",
      "send": "发送",
      "mode": "模式",
      "sessions": "会话",
      "sessionCount_one": "{count} 个会话",
      "sessionCount_other": "{count} 个会话",
      "noSessions": "还没有会话——发送一条消息即可开始。",
      "untitled": "未命名会话",
      "offlineBanner": "此设备已离线。重新连接前无法发送消息。",
      "status": {
        "idle": "空闲",
        "running": "运行中"
      }
    },
    "session": {
      "back": "返回设备",
      "thinking": "思考中",
      "thinkingAria": "思考中…",
      "you": "你",
      "send": "发送",
      "stop": "停止",
      "composerPlaceholder": "给 jcode 发消息…",
      "offlineBanner": "设备离线——重新连接前无法发送。",
      "streamError": "实时流中断——正在重连…",
      "reconnect": "重新连接",
      "approve": "批准",
      "approveAll": "始终允许",
      "deny": "拒绝",
      "toolDenied": "已拒绝",
      "askUser": "jcode 提了一个问题（在设备上回答）：",
      "agentStarted": "Agent 已开始",
      "agentDone": "Agent 已完成",
      "agentStopped": "已被用户停止",
      "agentFailed": "Agent 失败：{message}",
      "taskRunning": "会话运行中",
      "taskIdle": "会话空闲",
      "modeChanged": "模式已切换为 {mode}",
      "modelChanged": "模型已切换为 {model}",
      "sessionReset": "会话已重置",
      "todoUpdated": "Todos 已更新",
      "goalUpdated": "目标已更新：{objective}",
      "goalCleared": "目标已清除",
      "subagentStarted": "子 agent {name} 已开始",
      "subagentDone": "子 agent {name} 已完成",
      "subagentFailed": "子 agent {name} 失败",
      "sendFailed": "无法发送：{message}",
      "deviceOffline": "设备已离线",
      "emptyHistory": "此会话还没有事件。"
    },
    "pairing": {
      "start": "配对此客户端",
      "idle": {
        "title": "尚未设置端到端加密",
        "body": "将此浏览器与设备配对后，才能读取和发送加密的会话内容。密钥的明文只存在于设备上。"
      },
      "pending": {
        "title": "等待设备上批准",
        "body": "请在 10 分钟内在设备上批准此配对："
      },
      "denied": {
        "title": "配对被拒绝",
        "body": "设备拒绝了此配对请求。如是误操作，请重新发起。"
      },
      "expired": {
        "title": "配对已过期",
        "body": "配对请求未在 10 分钟内获得批准，请重新发起。"
      },
      "error": {
        "title": "配对失败",
        "body": "配对过程中出现问题，请重试。"
      }
    },
    "title": "授权设备",
    "lede": "一个 jcode CLI 正在请求登录此云端。输入它显示的验证码以继续。",
    "codeLabel": "设备验证码",
    "codeHint": "`jcode login` 显示的 8 位验证码，形如 XXXX-XXXX。",
    "codeRequired": "请输入 CLI 显示的验证码。",
    "continue": "继续",
    "confirmTitle": "这是你的设备吗？",
    "confirmBody": "仅当此验证码与你正在运行的 `jcode login` 显示的一致时才批准。",
    "approve": "批准",
    "deny": "拒绝",
    "approvedTitle": "设备已批准",
    "approvedBody": "CLI 现在可以完成登录了——你可以关闭此页面。",
    "deniedTitle": "设备已拒绝",
    "deniedBody": "登录请求已被拒绝，CLI 将停止等待。",
    "another": "授权另一台设备",
    "errorNotFound": "没有与该验证码匹配的待处理登录——它可能已过期。请重新运行 `jcode login`。",
    "errorAlreadyDecided": "该登录请求已被批准或拒绝。",
    "errorGeneric": "无法授权设备，请重试。"
  }
};
