// GENERATED by scripts/extract-device-locales.mjs from src/i18n/locales/zh-Hans.ts.
// Do not hand-edit; re-run the script after changing the console's device.* copy.
export default {
  "run": {
    "toolStatusDone": "完成",
    "toolStatus": {
      "running": "运行中",
      "failed": "失败",
      "queued": "排队中",
      "canceled": "已取消"
    },
    "unknownEvent": "未知事件：{type}",
    "permission": {
      "label": "权限",
      "required": "需要权限",
      "noAction": "无操作（已取消）",
      "timedOut": "已超时",
      "resolved": "已解决",
      "answered": "已回答 — 等待 agent…",
      "readonly": "只读 — 项目成员可以回答。"
    }
  },
  "device": {
    "compose": {
      "project": "项目目录",
      "model": "模型",
      "effort": "强度",
      "goal": "目标",
      "goalPlaceholder": "这个会话要达成什么？",
      "attachments": "附件",
      "attachAdd": "添加文件",
      "removeAttachment": "移除 {name}",
      "deviceDefault": "设备默认",
      "attachmentTooBig": "{name} 超过 2 MB——请选择更小的文件。",
      "attachmentTooMany": "每条消息最多 {max} 个附件。",
      "attachmentImage": "{name} 是图片——暂不支持图片附件。"
    },
    "list": {
      "title": "设备",
      "subtitle": "连接到你账号的 jcode 设备。可以把工作发送到任何一台在线机器。",
      "emptyTitle": "还没有设备",
      "emptyBody": "在一台机器上运行 `jcode login`，把它连接到 jcode Cloud。",
      "online": "在线",
      "offline": "离线",
      "lastSeen": "最近在线 {time}",
      "neverSeen": "从未上线",
      "loadErrorTitle": "无法加载设备",
      "servicePrincipal": "设备与用户账号绑定——请以用户身份登录，而不是使用控制台服务令牌。",
      "platformDesktop": "桌面端",
      "platformCli": "CLI",
      "e2ee": "端到端加密",
      "e2eeWithKeyGen": "端到端加密 · 密钥代数 {gen}"
    },
    "welcome": {
      "back": "设备",
      "newSession": "新会话",
      "composerPlaceholder": "向 jcode 提问…",
      "send": "发送",
      "mode": "模式",
      "sessions": "会话",
      "sessionCount_one": "{count} 个会话",
      "sessionCount_other": "{count} 个会话",
      "noSessions": "还没有会话——发送一条消息即可开始。",
      "untitled": "未命名会话",
      "offlineBanner": "此设备已离线。重新连接前无法发送消息。",
      "status": {
        "idle": "空闲",
        "running": "运行中"
      }
    },
    "session": {
      "back": "返回设备",
      "thinking": "思考中",
      "thinkingAria": "思考中…",
      "you": "你",
      "send": "发送",
      "stop": "停止",
      "composerPlaceholder": "给 jcode 发消息…",
      "offlineBanner": "设备离线——重新连接前无法发送。",
      "streamError": "实时流中断——正在重连…",
      "reconnect": "重新连接",
      "approve": "批准",
      "approveAll": "始终允许",
      "deny": "拒绝",
      "toolDenied": "已拒绝",
      "askUser": "jcode 提了一个问题（在设备上回答）：",
      "agentStarted": "Agent 已开始",
      "agentDone": "Agent 已完成",
      "agentStopped": "已被用户停止",
      "agentFailed": "Agent 失败：{message}",
      "taskRunning": "会话运行中",
      "taskIdle": "会话空闲",
      "modeChanged": "模式已切换为 {mode}",
      "modelChanged": "模型已切换为 {model}",
      "sessionReset": "会话已重置",
      "todoUpdated": "Todos 已更新",
      "goalUpdated": "目标已更新：{objective}",
      "goalCleared": "目标已清除",
      "subagentStarted": "子 agent {name} 已开始",
      "subagentDone": "子 agent {name} 已完成",
      "subagentFailed": "子 agent {name} 失败",
      "sendFailed": "无法发送：{message}",
      "deviceOffline": "设备已离线",
      "emptyHistory": "此会话还没有事件。",
      "source": {
        "console": "控制台",
        "mobile": "移动端",
        "desktop": "桌面端",
        "wechat": "微信",
        "local": "本地"
      }
    },
    "guide": {
      "entry": "使用指南",
      "title": "jcode 设备使用指南",
      "subtitle": "如何用 `jcode login` 接入一台机器，并从浏览器或手机 app 远程使用它。",
      "back": "返回设备列表",
      "shots": {
        "devices": "云控制台中的设备列表",
        "welcome": "设备页：发起新会话、浏览已有会话",
        "session": "从设备实时推送的会话",
        "offline": "设备离线时仍可查看历史",
        "login": "手机 app 的登录界面"
      },
      "what": {
        "title": "什么是\"设备\"？",
        "p1": "设备是一台运行 jcode（CLI 或桌面版）并通过 `jcode login` 登录到 jcode Cloud 的机器。接入后，你可以从云控制台或手机 app 远程查看和操作这台机器。",
        "p2": "云端只做中转：你的机器主动向云端发起连接，无需开放入站端口或 VPN。会话始终在你的机器上运行并保存。"
      },
      "quickstart": {
        "title": "快速上手",
        "p1": "在你要控制的机器上运行：",
        "code1": "jcode login",
        "p2": "CLI 会打印一个验证码和一个确认链接——在浏览器里确认登录。随后设备会自动连接，并出现在你的设备列表中。",
        "p3": "默认登录 https://cloud.j-code.net。self-host 时传入你的云端地址——必须使用 https（仅 localhost 开发场景允许 http）：",
        "code2": "jcode login --cloud https://your-cloud.example.com"
      },
      "remote": {
        "title": "远程使用设备",
        "p1": "打开设备列表，点进一台设备：可以发起新会话、实时跟进进行中的会话、停止运行、处理权限审批——和在机器本机上操作一致。",
        "p2": "设备离线时仍可翻看会话历史，但发消息和审批会被禁用，直到设备重新上线。"
      },
      "pairing": {
        "title": "配对与端到端加密",
        "p1": "会话内容端到端加密：云端只存密文和路由元数据，无法读取你的会话。新客户端（新浏览器或手机）必须先与设备配对，才能解密任何内容。",
        "p2": "在客户端发起配对，然后在设备上于 10 分钟内批准：",
        "code1": "jcode cloud pairings",
        "code2": "jcode cloud approve <pairing_id>",
        "p3": "`pairings` 列出待批准的请求及其备注名；`approve` 批准其中一个（拒绝对应 `jcode cloud deny <pairing_id>`）。"
      },
      "keys": {
        "title": "密钥与恢复",
        "p1": "加密密钥（CEK）在你的第一台设备上生成，永不明文离开你的设备。请备份一次 24 词恢复短语并妥善保管：",
        "code1": "jcode cloud key show-phrase",
        "p2": "如果所有设备都丢失，在新登录的设备上用短语恢复密钥：",
        "code2": "jcode cloud key recover",
        "p3": "需要更换密钥时（已配对的客户端需重新配对）：",
        "code3": "jcode cloud rotate-key"
      },
      "commands": {
        "title": "常用命令",
        "p1": "以下命令都在设备上运行：",
        "rows": {
          "login": "把本机登录到 jcode Cloud（设备码流程）。",
          "loginStatus": "显示当前登录状态并退出。",
          "logout": "退出登录：吊销设备令牌并清除本地凭据。",
          "cloudStatus": "显示云端地址、设备 id、密钥代数和连通性。",
          "pairings": "列出客户端发来的待批准配对请求。",
          "approve": "批准一个配对请求（把加密后的密钥交给客户端）。",
          "deny": "拒绝一个配对请求。",
          "showPhrase": "显示加密密钥的 24 词恢复短语。",
          "recover": "用恢复短语重建加密密钥。",
          "rotateKey": "生成新密钥（key_gen+1）；已配对客户端需重新配对。"
        },
        "e2eeNote": "端到端加密默认开启。需要临时关闭（明文上行，用于排查）时，在 `~/.jcode/config.json` 中设置 \"cloud\": { \"e2ee\": false } 并重启 `jcode web`。"
      }
    },
    "pairing": {
      "start": "配对此客户端",
      "idle": {
        "title": "尚未设置端到端加密",
        "body": "将此浏览器与设备配对后，才能读取和发送加密的会话内容。密钥的明文只存在于设备上。"
      },
      "pending": {
        "title": "等待设备上批准",
        "body": "请在 10 分钟内在设备上批准此配对："
      },
      "denied": {
        "title": "配对被拒绝",
        "body": "设备拒绝了此配对请求。如是误操作，请重新发起。"
      },
      "expired": {
        "title": "配对已过期",
        "body": "配对请求未在 10 分钟内获得批准，请重新发起。"
      },
      "gate": {
        "title": "需要配对",
        "body": "该设备已强制启用端到端加密。配对完成前，会话内容与控制不可用。"
      },
      "error": {
        "title": "配对失败",
        "body": "配对过程中出现问题，请重试。"
      }
    },
    "title": "授权设备",
    "lede": "一个 jcode CLI 正在请求登录此云端。输入它显示的验证码以继续。",
    "codeLabel": "设备验证码",
    "codeHint": "`jcode login` 显示的 8 位验证码，形如 XXXX-XXXX。",
    "codeRequired": "请输入 CLI 显示的验证码。",
    "continue": "继续",
    "confirmTitle": "这是你的设备吗？",
    "confirmBody": "仅当此验证码与你正在运行的 `jcode login` 显示的一致时才批准。",
    "approve": "批准",
    "deny": "拒绝",
    "approvedTitle": "设备已批准",
    "approvedBody": "CLI 现在可以完成登录了——你可以关闭此页面。",
    "deniedTitle": "设备已拒绝",
    "deniedBody": "登录请求已被拒绝，CLI 将停止等待。",
    "another": "授权另一台设备",
    "errorNotFound": "没有与该验证码匹配的待处理登录——它可能已过期。请重新运行 `jcode login`。",
    "errorAlreadyDecided": "该登录请求已被批准或拒绝。",
    "errorGeneric": "无法授权设备，请重试。"
  }
};
