// GENERATED by scripts/extract-device-locales.mjs from src/i18n/locales/zh-Hant.ts.
// Do not hand-edit; re-run the script after changing the console's device.* copy.
export default {
  "run": {
    "toolStatusDone": "完成",
    "toolStatus": {
      "running": "執行中",
      "failed": "失敗",
      "queued": "佇列中",
      "canceled": "已取消"
    },
    "unknownEvent": "未知事件：{type}",
    "permission": {
      "label": "權限",
      "required": "需要權限",
      "noAction": "無動作（已取消）",
      "timedOut": "已逾時",
      "resolved": "已處理",
      "answered": "已回覆 — 正在等待 agent…",
      "readonly": "唯讀 — 專案成員可以回覆。"
    }
  },
  "device": {
    "list": {
      "title": "裝置",
      "subtitle": "連線到你帳號的 jcode 裝置。可以將工作傳送到任何一台線上機器。",
      "emptyTitle": "尚無裝置",
      "emptyBody": "在一台機器上執行 `jcode login`，將它連線到 jcode Cloud。",
      "online": "線上",
      "offline": "離線",
      "lastSeen": "上次上線 {time}",
      "neverSeen": "從未上線",
      "loadErrorTitle": "無法載入裝置",
      "servicePrincipal": "裝置與使用者帳號綁定——請以使用者身份登入，而不是使用控制台服務權杖。"
    },
    "welcome": {
      "back": "裝置",
      "newSession": "新工作階段",
      "composerPlaceholder": "向 jcode 提問…",
      "send": "傳送",
      "mode": "模式",
      "sessions": "工作階段",
      "sessionCount_one": "{count} 個工作階段",
      "sessionCount_other": "{count} 個工作階段",
      "noSessions": "還沒有工作階段——傳送一則訊息即可開始。",
      "untitled": "未命名工作階段",
      "offlineBanner": "此裝置已離線。重新連線前無法傳送訊息。",
      "status": {
        "idle": "閒置",
        "running": "執行中"
      }
    },
    "session": {
      "back": "返回裝置",
      "thinking": "思考中",
      "thinkingAria": "思考中…",
      "you": "你",
      "send": "傳送",
      "stop": "停止",
      "composerPlaceholder": "傳訊息給 jcode…",
      "offlineBanner": "裝置離線——重新連線前無法傳送。",
      "streamError": "即時串流中斷——正在重新連線…",
      "reconnect": "重新連線",
      "approve": "批准",
      "approveAll": "一律允許",
      "deny": "拒絕",
      "toolDenied": "已拒絕",
      "askUser": "jcode 提出了一個問題（在裝置上回答）：",
      "agentStarted": "Agent 已開始",
      "agentDone": "Agent 已完成",
      "agentStopped": "已被使用者停止",
      "agentFailed": "Agent 失敗：{message}",
      "taskRunning": "工作階段執行中",
      "taskIdle": "工作階段閒置",
      "modeChanged": "模式已切換為 {mode}",
      "modelChanged": "模型已切換為 {model}",
      "sessionReset": "工作階段已重置",
      "todoUpdated": "Todos 已更新",
      "goalUpdated": "目標已更新：{objective}",
      "goalCleared": "目標已清除",
      "subagentStarted": "子 agent {name} 已開始",
      "subagentDone": "子 agent {name} 已完成",
      "subagentFailed": "子 agent {name} 失敗",
      "sendFailed": "無法傳送：{message}",
      "deviceOffline": "裝置已離線",
      "emptyHistory": "此工作階段還沒有事件。"
    },
    "pairing": {
      "start": "配對此用戶端",
      "idle": {
        "title": "尚未設定端對端加密",
        "body": "將此瀏覽器與裝置配對後，才能讀取和傳送加密的工作階段內容。金鑰的明文只存在於裝置上。"
      },
      "pending": {
        "title": "等待裝置上批准",
        "body": "請在 10 分鐘內於裝置上批准此配對："
      },
      "denied": {
        "title": "配對已被拒絕",
        "body": "裝置拒絕了此配對請求。如是誤操作，請重新發起。"
      },
      "expired": {
        "title": "配對已過期",
        "body": "配對請求未在 10 分鐘內獲得批准，請重新發起。"
      },
      "error": {
        "title": "配對失敗",
        "body": "配對過程中出現問題，請重試。"
      }
    },
    "title": "授權裝置",
    "lede": "一個 jcode CLI 正在請求登入此雲端。輸入它顯示的驗證碼以繼續。",
    "codeLabel": "裝置驗證碼",
    "codeHint": "`jcode login` 顯示的 8 位驗證碼，形如 XXXX-XXXX。",
    "codeRequired": "請輸入 CLI 顯示的驗證碼。",
    "continue": "繼續",
    "confirmTitle": "這是你的裝置嗎？",
    "confirmBody": "僅當此驗證碼與你正在執行的 `jcode login` 顯示的一致時才批准。",
    "approve": "批准",
    "deny": "拒絕",
    "approvedTitle": "裝置已批准",
    "approvedBody": "CLI 現在可以完成登入了——你可以關閉此頁面。",
    "deniedTitle": "裝置已拒絕",
    "deniedBody": "登入請求已被拒絕，CLI 將停止等待。",
    "another": "授權另一台裝置",
    "errorNotFound": "沒有與該驗證碼匹配的待處理登入——它可能已過期。請重新執行 `jcode login`。",
    "errorAlreadyDecided": "該登入請求已被批准或拒絕。",
    "errorGeneric": "無法授權裝置，請重試。"
  }
};
