-- 0039_desktop_config_mesh: account-scoped Desktop configuration sync.
--
-- The Account Sync Key (ASK) is generated by an approved Desktop and is never
-- uploaded in plaintext. The control plane stores only an X25519-wrapped copy
-- per approved device. Provider configurations are independently encrypted
-- with the ASK and CAS-versioned so two Desktops can merge without replacing
-- an unrelated provider.

CREATE TABLE IF NOT EXISTS account_sync_keys (
    user_id    TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    key_gen    INTEGER NOT NULL CHECK (key_gen >= 1),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS account_sync_key_wraps (
    user_id               TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id             TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    key_gen               INTEGER NOT NULL CHECK (key_gen >= 1),
    status                TEXT NOT NULL CHECK (status IN ('pending','approved','denied')),
    wrap                   BYTEA,
    approved_by_device_id TEXT REFERENCES devices(id) ON DELETE SET NULL,
    created_at             TIMESTAMPTZ NOT NULL,
    resolved_at            TIMESTAMPTZ,
    PRIMARY KEY (user_id, device_id),
    CHECK (
        (status = 'approved' AND wrap IS NOT NULL AND resolved_at IS NOT NULL)
        OR
        (status = 'pending' AND wrap IS NULL AND resolved_at IS NULL)
        OR
        (status = 'denied' AND wrap IS NULL AND resolved_at IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS account_sync_key_wraps_pending_idx
    ON account_sync_key_wraps (user_id, status, created_at);

CREATE TABLE IF NOT EXISTS account_provider_configs (
    user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL,
    version    BIGINT NOT NULL CHECK (version >= 1),
    envelope   BYTEA NOT NULL,
    deleted    BOOLEAN NOT NULL DEFAULT false,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (user_id, provider_id)
);

CREATE INDEX IF NOT EXISTS account_provider_configs_updated_idx
    ON account_provider_configs (user_id, updated_at);
